version: '3.6'
services:
  db:
    ports:
      - 54320:5432

  # https://hub.docker.com/r/neimheadh/phppgadmin
  phppgadmin:
    image: neimheadh/phppgadmin:latest
    labels:
      traefik.enable: true
      traefik.http.services.pma.loadbalancer.server.port: 80
      traefik.http.routers.pma.rule: "Host(`pga.localhost.tv`)"
      traefik.http.routers.pma.entrypoints: web
    ports:
      - "80"
    environment:
      POSTGRES_HOST: ${PG_HOST}
      POSTGRES_PORT: ${PG_PORT}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASS: ${PG_PASSWORD}
    restart: always
    volumes:
      - ./.docker/phppgadmin/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
    networks:
      sfdemopg:
        aliases:
          - pga.localhost.tv

  maildev:
    image: djfarrelly/maildev
    labels:
      traefik.enable: true
      traefik.http.services.maildev.loadbalancer.server.port: 80
      traefik.http.routers.maildev.rule: "Host(`maildev.localhost.tv`)"
    ports:
      - 80
      - 25
    networks:
      sfdemopg:
        aliases:
          - maildev.localhost.tv

  traefik:
    image: traefik:v2.3
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - sfdemopg

volumes:
  pgdata: #Keep database on local docker storage
