version: '3.6'
services:
  web:
    image: nginx
    labels:
      traefik.enable: true
      traefik.docker.network: sfdemopg
      traefik.http.services.www.loadbalancer.server.port: 80
      traefik.http.routers.www.rule: "Host(`demo.localhost.tv`)"
      traefik.http.routers.www.entrypoints: web
    ports:
      - 80
      - 443
    volumes:
      - ./project:/var/www
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/demo.conf:/etc/nginx/sites-enabled/demo.conf
    restart: always
    depends_on:
      - php
    networks:
      sfdemopg:
        aliases:
          - demo.localhost.tv

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432
    networks:
      - sfdemopg

  php:
    build: .docker/php
    restart: always
    environment:
      PG_HOST: ${PG_HOST}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_PORT: ${PG_PORT}
      PG_DATABASE: ${PG_DATABASE}
    volumes:
      - ./project:/var/www
      - ${COMPOSER_HOME:-/tmp/composer}:/home/www-data/.composer # Share composer cache
    depends_on:
      - db
    user: "${VOLUME_USER_ID:-www-data}:www-data"
    networks:
      - sfdemopg

networks:
  sfdemopg:
    driver: bridge
